[package]
name = "chess2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
rayon = "1.10.0"
strum = "0.27.0"
strum_macros = "0.27.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
